dependencies:
  - name: postgresql
    version: 0.15.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
  - name: redis
    version: 3.6.5
    repository: https://kubernetes-charts.storage.googleapis.com/
